[package]
name = "nanite"
version = "0.0.1"
authors = ["Matthew J Perez <matt@mperez.io>"]
edition = "2018"
description = "Toolkit for the Nano cryptocurrency"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mattjperez/nanite"
keywords = ["crypto", "blockchain"]

[dependencies]
